### ISSUE TITLE
Picture/Audio stub?

### ISSUE THREAD

**Issue by criztovyl** [TelepathyQt/telepathy-morse#13]
As Morse can't receive images/audio (yet) what's about a message like "Images aren't supported yet"  when receiving images/audio?
( Feature Request :) )

**Comment by Kaffeine** [comment]
That would be simple. Even more, TelegramQt have initial support for media messages receiving (it really works). The problem is on Telepathy side — there is no clients with media message support (IIRC the one existed for Maemo or MeeGo).

So — accepted. Sadly I'm busy this season, but I'll do it sometime soon.

**Comment by criztovyl** [comment]
May be you could point me somewhere and I could help :)

**Comment by TemeV** [comment]
It is now implemented in a5f5a126b06c37d35381126140946e7a553df973
