### ISSUE TITLE
Can't chat with users only known by username (Empathy)

### ISSUE THREAD

**Issue by criztovyl** [TelepathyQt/telepathy-morse#22]
Hello, 
as in title.

I receive the messages from the user, can open a chat window but when I send an answer it does not send, it appears in the (local) chat but not in Telgram Web nor in my App.  
Furthermore the contact does not appear when I use "Start Conversation" (or likely, using German locale), only that generic offline named-as-I-typed user that never works/worked. (I can send messages in chat window, but they don't send.)

Debian Testing, Empathy 3.12.11
telepathy-morse and friends freshly built from master.

**Comment by Kaffeine** [comment]
Hi.

This is expected issue. There is no documentation for many parts of API and someone had to reverse-engineer it from e.g. java client. This particular issue can be easy to fix (actually — to implement missing bits), but I have no "contact known only by username". I will try to fix the issue next weekend (now I'm working on yet another undocumented feature).

The first interesting method is contacts.resolveUsername. Of course, it is not listed at [all methods](https://core.telegram.org/methods) page, but at least it's present at the [outdated, but latest available scheme](https://core.telegram.org/schema) page. Sure, there is no doc: https://core.telegram.org/method/contacts.resolveUsername

**Comment by criztovyl** [comment]
I could be your "known by username only" :D Same as here: @criztovyl

Thanks for your effords :)

**Comment by criztovyl** [comment]
Telegram iOS [TGResolveDomainActor.m L66ff.](https://github.com/peter-iakovlev/Telegram/blob/58ce610e95aec809a847e928e06c01cffbd317a1/Telegraph/TGResolveDomainActor.m#L66)
Telegram WP [MTProtoService.Contacts.cs L14ff.](http://telegram.org/resources/telegram_wp.src.zip Telegram WP/Telegram WP/HexRequest/HexRequest/Services/MTProtoService.Contacts.cs:14)

In some schemes I found `contacts.resolveUsername#f93ccba3 username:string = contacts.ResolvedPeer;`

Maybe that helps.

**Comment by criztovyl** [comment]
Also, https://github.com/majn/tgl/blob/bec66c25d52368695e10625f956de5250a2d836d/queries.c#L2195
Thanks to telegram-purple Telegram group :)

**Comment by Kaffeine** [comment]
It's not a big issue to figure out the syntax of the function from a client source. Official documentation have nothing after layer 23 (protocol version), but I found the scheme for layer 51 at 
https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/mtproto/scheme.tl

On layer 23 "resolveUsername" defined as `contacts.resolveUsername#bf0131c username:string = User;`. Take a note, that it returns User object instead of ResolverPeer.

I'm in process of updating to layer 29, which is the nearest layer after the documented and mostly working layer 23. It seems that server do not actually support outdated schemes, so we need to update the layer. Currently all changed (since layer 23) methods and objects do not behave properly. Look at https://github.com/Kaffeine/telegram-qt/issues/14 for the first of the plenty of known issues.

The main problem on layer 29 is invalid updates received from server. I'm investigating it.
It looks like server send updated version of some object, while the code, generated from the layer 29 scheme, reads it in old manner.

**Comment by Kaffeine** [comment]
@criztovyl Outgoing messaging works well, but there was an issue with incoming messages: there is only userId in the messages, but we need to know accessHash to get user info (first, last names, avatar and so on). I changed "secret info" to also save userId/accessHash pairs for all users with a hash (contacts have no accessHash).

Now I need to check that it works. Can you send me a message pls?

**Comment by Kaffeine** [comment]
Ok, doesn't work yet.
Well, I have an idea to use getDialogs().

**Comment by Kaffeine** [comment]
Should work after https://github.com/Kaffeine/telegram-qt/commit/3d4dbd97aa3738c664073bb64f02ad490d588506

Feel free to reopen, if it still reproducible (works for me in several test cases.)
