### ISSUE TITLE
Implement WebPage messages

### ISSUE THREAD

**Issue by dirusulixes** [TelepathyQt/telepathy-morse#38]
I only tested via Empathy, therefore I do not know if it is a general issue or not, but links sent to me by contacts are not shown in chat. Links I sent are shown normally.

**Comment by Kaffeine** [comment]
Hello.

I can not check it right now, but I think you're right. I will implement it soon, thank you!

**Comment by Kaffeine** [comment]
I just worked this out, I will push it tomorrow. You'll have to update both telepathy-morse and telegram-qt.

**Comment by Kaffeine** [comment]
Commit 942915560ae816d814c0db3e3a7d1e2fbe325aa9
This change will be released in version 0.2.0, because I had to add the implementation to TelegramQt-0.2.0 (which is not released yet).

You can build TelegramQt and Telepathy-Morse from git master branches to test it right now, or wait for 0.2.0 release (planned for December 12, 2016).
