### ISSUE TITLE
Better mobile number entry

### ISSUE THREAD

**Issue by ghost** [TelepathyQt/telepathy-morse#49]
It can be confusing for the user on how to enter your mobile number.  On other apps, they offer a pull down list with country codes and a box you enter your full local number.  The app then formats the number correctly and passes it to the backend.  Is it possible to do this?

If that is complicated, maybe as an easy fix, if you could display a sample or brief description of how to enter the number.  I had to do trial and error, which didn't work due to me putting + and/or extra zeros in!

**Comment by Kaffeine** [comment]
Telepathy-Morse has no settings plug-ins. The issue is in the scope of the UI developer:
- [KDE Telepathy](https://bugs.kde.org/buglist.cgi?bug_status=__open__&component=accounts-kcm&product=telepathy)
- [Empathy](https://bugzilla.gnome.org//buglist.cgi?bug_status=__open__&component=accounts&product=empathy)
- [Sailfish OS](https://github.com/Kaffeine/sailfish-settings-accounts-extensions-telegram/)
