### ISSUE TITLE
Chatrooms are not working with Empathy

### ISSUE THREAD

**Issue by TemeV** [TelepathyQt/telepathy-morse#7]
I can see a list of group chats and join a room with Empathy, but I don't see any messages or participants and the title of the room is just "chat1". Chat window looks like this: https://dl.dropboxusercontent.com/u/11381336/Screenshot-chat1.png

Sending messages works though, but I can't see even the message I have just sent.

**Comment by Kaffeine** [comment]
I tried to solve the issue, but have not success.
I used Bustle to compare DBus messages for Empathy with the one for KDE Telepathy and I didn't find anything notable. I tried to read the source of Empathy to figure out, what it needs to work, but drown in the "yet another telepathy stack". I'm coming to the idea to ask Empathy developers for some hint. Will do it sometime soon.

**Comment by Kaffeine** [comment]
Update:
Thanks to Tiago Salem Herrmann, the dev of Telepathy-Hanging, we got to know that the problem is inside telepathy-glib contacts handling code, but the issue can be workarounded with some extra work in TelepathyQt.
We have some experimental solutions, but I'd like to rework groups interface in TelepathyQt.
That said, telepathy-glib (read Empathy) workarounded group chat will be available with TelepathyQt-0.9.7 release.

**Comment by Kaffeine** [comment]
I think I just fixed it (7ea76802dab36c70bc28bf0e4b0095d4383694fc).
Can you confirm? You need TelepathyQt from git for this.

You can use the bundling script to download and compile everything in one package. I didn't implemented installation, though. https://github.com/TelepathyQt/telepathy-qt/wiki/Project-with-CMs-as-examples

**Comment by TemeV** [comment]
I tested this with Empathy, and it works. Thanks!
